### ISSUE TITLE
[BUG - Dev2.0]

### ISSUE THREAD

**Issue by narknon** [UE4SS-RE/RE-UE4SS#17]
**Branch or Release**
Dev2.0

**Game and Engine Version**
Deep Rock Galactic

**Describe the bug**
Crash on launch while UE4SS initializes the ConsoleEnablerMod

**To Reproduce**
1. Launch game with ConsoleEnablerMod enabled.

**Expected behavior**
Initialize mod and launch.

**Screenshots and UE4SS Log**
![image](https://user-images.githubusercontent.com/73571427/205114172-25bbe582-5e0a-461c-87c6-db8c3d604bf8.png)
![image](https://user-images.githubusercontent.com/73571427/205114664-e92410c8-3821-4db3-ba0e-fec88f1006b8.png)
![image](https://user-images.githubusercontent.com/73571427/205114937-cf117f8a-ac9d-4474-b945-bf381e171341.png)
![image](https://user-images.githubusercontent.com/73571427/205114994-d43ab3f8-e597-494a-bc5c-087d085fcda3.png)
![image](https://user-images.githubusercontent.com/73571427/205115028-a29a518f-2243-46ef-bbdf-27698c0a1012.png)
![image](https://user-images.githubusercontent.com/73571427/205115063-43f434bc-cb6e-4f8b-ae55-cd9470fe1908.png)
![image](https://user-images.githubusercontent.com/73571427/205115088-7323294c-896d-4174-98a9-fd4b5fdd13b5.png)

**Desktop (please complete the following information):**
Win11

**Additional context**
Does not crash with ConsoleEnablerMod disabled.  Per Buckminster, does not crash with Release 2.0.
Possibly related to DRG using 3 console buttons, some of which are non-standard characters:
![image](https://user-images.githubusercontent.com/73571427/205115992-d2b372cc-c99f-46c3-b9a9-20f266c0a458.png)

![image](https://user-images.githubusercontent.com/73571427/205116042-ef6bd4fa-699b-4882-9c0f-3608686b7fc7.png)

**Comment by narknon** [comment]
Appears to have been introduced in 3e7d030f167fa4a5c6611c1729b1091138e3e0dc

**Comment by narknon** [comment]
Introduced in f6f0e7b5d7c8802c063958a522c8416addc86ccb

**Comment by MostlyBored** [comment]
I can confirm that this happens due to the non-ascii console keys that Deep Rock Galactic uses.
The problem is that Lua can't handle non-ascii strings so all strings that interact with Lua get converted to ascii but this conversion is not done in a safe way as it assumes that no strings contain any non-ascii characters.

I'm preparing a fix in the `Helpers` submodule for this right now to fix this.

**Comment by MostlyBored** [comment]
I've submitted the fix and it can be found here: https://github.com/UE4SS-RE/Helpers/pull/1
Try it and see if it solves the problem.

**Comment by narknon** [comment]
Thank you.  Any idea why they were properly being replaced with ? in release configuration builds but not debug?

**Comment by MostlyBored** [comment]
> Thank you. Any idea why they were properly being replaced with ? in release configuration builds but not debug?

No, I'm unsure as to why it worked in release but I doubt the replacement with `?` was proper.

**Comment by barkermn01** [comment]
I seem to recall release configurations using a different method in Windows DLL's and I think it depends on the version of windows, I seem to recall windows has some safety nets for Older Applications that don't support UTF8 or above, and when in Debug MS don't want you relying on these because they want you to fix your application to support Unicode.,

@MostlyBored is there any way that instead of just replacing them with `!` could we replace them with a \u Unicode notation?

**Comment by MostlyBored** [comment]
> I seem to recall release configurations using a different method in Windows DLL's and I think it depends on the version of windows, I seem to recall windows has some safety nets for Older Applications that don't support UTF8 or above, and when in Debug MS don't want you relying on these because they want you to fix your application to support Unicode.,
> 
> @MostlyBored is there any way that instead of just replacing them with `!` could we replace them with a \u Unicode notation?

We need to use something that Lua can use.
Lua doesn't understand unicode unfortunately.

I've hopefully got a better solution though, check https://github.com/UE4SS-RE/Helpers/pull/2.

**Comment by narknon** [comment]
The substantive aspects of this issue are now fixed on Dev, so closing for now.  May add handling of additional characters as a todo.

Thank you for the contributions
