### ISSUE TITLE
[UESDK] Get access to FVector2D

### ISSUE THREAD

**Issue by Rebel40** [UE4SS-RE/RE-UE4SS#308]
Hello,

I'm working on a proof of concept to let enduser be able to adjust widgets.
For this i need to call functions Widget::SetRenderTranslation and Widget::SetRenderScale which expects an FVector2D as argument.
Can this be added to UESDK?

**Comment by UE4SS** [comment]
Due to UE using doubles in 5.X for some structs (including FVector2D) and floats in 4.X, it would have the same problem as FVector.

UE4SS has runtime support for all supported engine versions but C++ doesn't support different versions of structs with the same name at runtime so we have to choose whether our structs use doubles or floats at compile time which means that support for UE functions that take those as a param is a bit shaky.
Basically, we implement the largest struct we can (so for FVector that's 3xSize of double), and we convert floats to and from doubles when constructed and used.

One problem is that if you pass this FVector directly to a UE function, it would only work in 5.X since 4.X expects floats.

Another problem, which isn't solved as easily as the above problem by just having a wrapper and converting the struct at runtime to a version with a different name that uses floats, is the fact that we can't do this easily for containers.
We are unable to support containers (like TMap, TArray, or even TPair) with these structs at all unless the game just happens to be using a compatible engine version which obviously will never be guaranteed and we don't have a way right not to choose the engine version at compile time.

Since this is a fairly simple struct, I would actually recommend that you implement it yourself since we can't satisfy everyone without having some way of selecting which version of the struct you want at compile time.

**Comment by Rebel40** [comment]
Thanks for the awnser, and i'm very sorry, added this feature request to the wrong repository..... ;-(((
consider this request as never asked...
Best regards
