### ISSUE TITLE
[BUG - Release] Ace Combat 7 | Couldn't spawn player: Failed to find PlayerStart

### ISSUE THREAD

**Issue by kosnag** [UE4SS-RE/RE-UE4SS#311]
**Branch or Release**
Release

**Game and Engine Version**
Ace Combat 7
UE4.18

**Describe the bug**
Game crashes instantly after launching

**To Reproduce**
Launch a game with installed UE4SS higher than 2.3.1 (2.3.1 is latest version what works fine)

**Expected behavior**
Game must not crash after launching

**Screenshots and UE4SS Log**
[UE4SS.log](https://github.com/UE4SS-RE/RE-UE4SS/files/14066834/UE4SS.log)
[Game.log](https://github.com/UE4SS-RE/RE-UE4SS/files/14066842/Game.log)
![26_18 54 15](https://github.com/UE4SS-RE/RE-UE4SS/assets/63012171/bc57712e-794c-4a71-a88b-32fe56e4268f)

**Desktop (please complete the following information):**
 - OS: Windows 10 
 - CPU: Intel Core i5 10400F
 - GPU: AMD Radeon RX6600XT
 - RAM: 2x8Gb DDR4 3600Mhz

**Additional context**
If I remember correctly, devs used custom version of UE4.18 for development.
Used 2.5.2 from Releases tab.

**Comment by UE4SS** [comment]
The only advice I have is to try an experimental build, here's the latest one: https://github.com/UE4SS-RE/RE-UE4SS/releases/download/experimental/UE4SS_v2.5.2-577-gddee25c.zip
You need both `dwmapi.dll` and `UE4SS.dll` and you also need to remove the xinput dll from any other UE4SS releases.

If the game is using a customized engine, then the experimental build isn't likely to solve the problem but it's worth a try.
If it doesn't solve the problem, hopefully someone else can help you.

**Comment by kosnag** [comment]
Unfortunately still crash with same error.

**Comment by UE4SS** [comment]
Another thing you can try is to disable all mods, and if that works, try re-enabling them one-by-one until it crashes to find out which mod is the problem.

**Comment by UE4SS** [comment]
> Nope. Even with all mods are being disabled in mods.txt, still same fatal error at start up.

We could maybe debug this problem if you use this experimental build: https://github.com/UE4SS-RE/RE-UE4SS/releases/download/experimental/zDEV-UE4SS_v2.5.2-594-gc053439.zip
You'll need to open `UE4SS-settings.ini` and set `FullMemoryDump` to 1 and then start the game.
When the game crashes, a `.dmp` file will be generated and you'll need to upload this file somewhere and link it here.
Beware that the file will probably be 2 GB+ in size and might take a while to generate so don't force close the game if it appears to be frozen.
You might also need to include the exe of the game in the upload, I'm not sure if that's strictly required for these `.dmp` files to work.

@localcc Do you know if the game exe is required in order to debug UE4SS using a .dmp file ?
I was having problems with another game where I had a .dmp file without the game executable and I couldn't see the call stack for some reason.
I don't know if I messed something up, or if the sender messed something up, or if that's expected behavior.

**Comment by localcc** [comment]
Game exe should not be required for debugging using the crash dump. The most common cause of not seeing the call stack is mismatch between the DLL and pdb.

**Comment by kosnag** [comment]
It's not generates dump file...
But here is executable file - [drive.google.com/file/d/1B3U-m5K4QYrBY9f7WweRNdJ3sIUE8fKX/view](https://drive.google.com/file/d/1B3U-m5K4QYrBY9f7WweRNdJ3sIUE8fKX/view?usp=sharing)

**Comment by UE4SS** [comment]
> It's not generates dump file...

Did you override your existing `UE4SS-settings.ini` with the one that comes with the experimental build ?
There's the `EnableDumping` option that also needs to be set to 1 in the ini file, and that's a fairly recent addition to the ini file so it might not be in your file if you didn't replace it with the file from the experimental build.

**Comment by UE4SS** [comment]
> Yes. I'm fully uninstalled old version of UE4SS and installed this. EnableDumping and FullMemoryDump both are true (1). All mods disabled via mods.txt config file.

Then I'm not sure why no .dmp file is being generated.
@localcc Any ideas ?

**Comment by kosnag** [comment]
"bUseUObjectArrayCache = false" also doesn't helps

**Comment by kosnag** [comment]
Want to make update. Game crashes instantly only if used xinput (for 2.5.2) or dwmapi (3.0.0). If inject UE4SS via CheatEngine - crash happens only if i move from menu into mission or smth else.
And also dumps still not generated. Another question - where they are (dumps) must be?

**Comment by UE4SS** [comment]
> Want to make update. Game crashes instantly only if used xinput (for 2.5.2) or dwmapi (3.0.0). If inject UE4SS via CheatEngine - crash happens only if i move from menu into mission or smth else. And also dumps still not generated. Another question - where they are (dumps) must be?

Dumps get generated in the same place where the game exe is.

**Comment by kosnag** [comment]
![22_23 12 39_Ace7Game](https://github.com/UE4SS-RE/RE-UE4SS/assets/63012171/26cad882-c442-4360-8090-d819f5c417b2)
Fixed in 3.0.1
