### ISSUE TITLE
[BUG] Experimental build counter is broken

### ISSUE THREAD

**Issue by UE4SS** [UE4SS-RE/RE-UE4SS#350]
Go to https://github.com/UE4SS-RE/RE-UE4SS/releases/tag/experimental and scroll down to the new 3.0.0 experimental builds and you'll see the names are all `zDEV-UE4SS_v3.0.0-1-<commit_hash>.zip `.
The `v3.0.0.-1` is the problem, the `1` isn't counting up any longer.

**Comment by Buckminsterfullerene02** [comment]
It's not broken, you ran the make experimental release action manually for differen't branches, and the build script runs `git describe --tags` only for main branch, which up until that point only had 1 commit on it since v3.0.0 tag. So it makes sense why the counter is like that. 

It wouldn't make sense for the build script to take into account all commits on all branches as then the numbers would very quickly become out of sync as branch commits are squashed or deleted without merge etc.
