### ISSUE TITLE
[BUG - Release] Tales of Arise: Failed to find `GUObjectArray, FName::FName`, crash when using custom AOBs

### ISSUE THREAD

**Issue by emoose** [UE4SS-RE/RE-UE4SS#410]
**Branch or Release**
v3.0.1

**Game and Engine Version**
Tales of Arise 2023-12 update, UE 4.20

**Describe the bug**
Log file fills up with scan attempts, seems to keep failing with `Failed to find GUObjectArray` & `Failed to find FName::FName(wchar_t*)`
Game launches but UE4SS isn't active.

I tried creating LUA files to find those signatures, but with these I get a fatal error, and UE4SS.log mentions that `Lua script 'FName_Constructor.lua' did not return a valid address for FName::FName.`

In the game EXE it looks like most FName uses are calling straight into some internal ctor that has 6 arguments, pattern below should be matching a 3 arg (thisptr / char* / flags) func, which then just calls into the 6 arg func - seems to match both char* and wchar_t* versions, not really sure why it's not working here.

FName_Constructor.lua:
```
function Register()
    return "40 53 48 83 EC 30 48 8B D9 48 85 D2 74 ?? 45 8B C8 C7 44 24 28 FF FF FF FF"
end

function OnMatchFound(MatchAddress)
    return MatchAddress
end
```

GUObjectArray.lua:
```
function Register()
    return "CC 4C 8B C9 4C 8D 15 ?? ?? ?? ?? 4C 89 11 45 84 C0"
end

function OnMatchFound(MatchAddress)
    local LeaInstr = MatchAddress + 0x4
    local NextInstr = LeaInstr + 0x7
    local Offset = LeaInstr + 0x3
    local AddressLoaded = NextInstr + DerefToInt32(Offset)
    return AddressLoaded
end
```

**Comment by UE4SS** [comment]
You should share the log file.
It's normal that there's lots of spam about AOBs not being found, it's continuously scanning an reporting the status.
You need to look at the very bottom of the file to see if FName::FName and GUObjectArray were eventually found.

**Comment by emoose** [comment]
Seems to go up to attempt 193 but then times out :(

[UE4SS.log](https://github.com/UE4SS-RE/RE-UE4SS/files/14426392/UE4SS.log)

**Comment by UE4SS** [comment]
I think this has to do with `BPModLoaderMod`.
Can you set `BPModLoaderMod` to 0 in mods.txt and see if the problem goes away ?

**Comment by UE4SS** [comment]
Do you have a `.dmp` file in the same directory that has UE4SS.log ?

**Comment by emoose** [comment]
No luck changing mods.txt, no dmp file either - I can get VS to create one but it ends up at 4GB+ :/

**Comment by UE4SS** [comment]
The size of the dmp file is fine if you can upload it somewhere other than GitHub because GitHub probably doesn't allow files that large to be uploaded in an issue.
It's large because it contains the full memory of the program, and that can help immensely when debugging.
If you can't upload it anywhere, there should be an option somewhere to not dump the full memory, something like "Minidump" vs "Minidump with heap" and that should bring the size down enough to be uploaded directly to GitHub.

**Comment by emoose** [comment]
Oh I just noticed there is a UE4Minidump created in games appdata folder, seems to show the same call stack as above:
[TalesOfAriseMinidump.zip](https://github.com/UE4SS-RE/RE-UE4SS/files/14442140/TalesOfAriseMinidump.zip)
Pretty small though, if that's missing anything let me know and I'll try making it with VS instead.

**Comment by UE4SS** [comment]
> Oh I just noticed there is a UE4Minidump created in games appdata folder, loading it in VS seems to show same call stack as above (once I point it to the UE4SS.dll/pdb, this was with zDEV-UE4SS_v3.0.1.zip): [TalesOfAriseMinidump.zip](https://github.com/UE4SS-RE/RE-UE4SS/files/14442152/TalesOfAriseMinidump.zip) Pretty small though, if that's missing anything let me know and I'll try making it with VS instead.

Typically a .dmp file only needs UE4SS.dll/pdb and it will load properly but with these `UE4Minidump` files won't load properly for me, there are always missing call-stack frames because of missing binary files, the entire call-stack is hidden.
Try make one with VS.
If you want to save time (if your internet is bad) you can try a small one (no memory/heap dump) first so that I can see if it will have the same problem as the UE4Minidump.

**Comment by emoose** [comment]
Ah too bad, well this time VS dump came in at 1GB, hopefully can be of more use: https://www.mediafire.com/file/1f11io9wcmmnqg1/Tales_of_Arise_withHeap.7z/file

**Comment by UE4SS** [comment]
According to your dump, the parameters passed to `HookedLoadMap` are incorrect or corrupt or something.
Can you check if this version of UE4SS works ? https://github.com/UE4SS-RE/RE-UE4SS/releases/download/experimental/zDEV-UE4SS_v2.5.2-594-gc053439.zip
You'll need to either copy the BPModLoaderMod as well from that zip or turn that mod off.

**Comment by emoose** [comment]
Steam ver seems to start up fine with that build + the LUAs, and UE4SS is active, without the LUAs it fails to find GUObject/FName as before.

With game pass it doesn't fatal error any more, but UE4SS doesn't load in, log has a pretty weird error:

```
[18:34:00] PS Scan attempt 1
[18:34:00] [PS] Reading image
[18:34:00] [PS] Starting scan
[18:34:00] [PS] Scan finished in 237.7745ms
[18:34:00] [PS] Found GUObjectArray: 0x7ff7b265fb30
[18:34:00] [PS] Found GMalloc: 0x7ff7b2cde580
[18:34:00] [PS] Found FName::ToString: 0x7ff7b019f4c0
[18:34:00] [PS] Found FName::FName(wchar_t*): 0x7ff7ae842330
[18:34:00] [PS] Found StaticConstructObject_Internal: 0x7ff7aea4e780
[18:34:00] [PS] Found FText::FText(FString&&): 0x7ff7ae76c1f0
[18:34:00] PS scan successful
[18:34:00] Running first pass of Lua override scans
[18:34:00] Lua Scan attempt 1
[18:34:00] Fatal Error: [SinglePassScanner::start_scan] Could not merge containers. Either there were not containers to merge or there was an internal error.
```

**Comment by UE4SS** [comment]
The `LoadMap` function is a virtual function in UEngine, and it's likely that the vtable in this game is different than the default vtable for 4.20, and since we use the UEngine vtable to locate `LoadMap`, we're likely finding the wrong function.

Can you check if UE4SS detects 4.20 as the version on its own without setting it in the ini file ?

If it doesn't, that might be the problem and manually setting it to 4.20 should fix it.

If it does, then you'll most likely have to reverse engineer the vtable for UEngine and supply a `VTableLayout.ini` file with a fixed vtable for UEngine.
It might be worth it to look at what the ASM for `LoadMap` looks like in default 4.20 first and compare it to whatever UE4SS thinks is `LoadMap` to confirm that it finds the wrong function.
That file can be found in https://github.com/UE4SS-RE/RE-UE4SS/tree/main/assets/VTableLayoutTemplates and you'll need to choose the version closest to your game and then rename the file to `VTableLayout.ini` and put it next to UE4SS.dll.

Also it looks like we're missing UEngine in our VTableLayout files.
That means we'll have to regenerate with UVTD and update the files at the link above and this might take a while because I'm not able to do it currently so someone else might have to do it.

**Comment by UE4SS** [comment]
Actually, I figured out how to generate the files and they are available here for now: https://github.com/UE4SS-RE/RE-UE4SS/tree/vtabletemplate-update-missing-5.1/assets/VTableLayoutTemplates

**Comment by emoose** [comment]
With Steam it seems to detect as 4.20 without adding that to INI, but with game pass that scan seems to fail and I had to add to INI instead.

Thanks for the tip with VTableLayout and the updated INI, just tried adding a single func above LoadMap there and seems like Steam ver is loading in fine with 3.0.1 now 🐱 

I can't be sure where they might have added the extra func though, do you know if there's likely to be other funcs used from the vtable too which might break, or is it only really used for getting LoadMap?

**Comment by UE4SS** [comment]
> I can't be sure where they might have added the extra func though, do you know if there's likely to be other funcs used from the vtable too which might break, or is it only really used for getting LoadMap?

We only use the UEngine vtable for LoadMap currently.
We know from your testing that there's one extra function somewhere either in the UEngine vtable or the UObject vtable and since we use the UObject vtable to find `ProcessEvent` and nothing else appears to be broken, we can be fairly sure that it's the UEngine vtable that's been changed.
The only way to narrow down exactly where in the vtable they added a new function is to look at each and every function before LoadMap and see if they match the ASM of what the function is supposed to be, but considering what I just said above, it would be a waste to do this now.

**Comment by UE4SS** [comment]
Oh and in case you're wondering why the other build that I linked works, it's because it's an older version from before we added support for `LoadMap` hooking.

**Comment by UE4SS** [comment]
An alternative fix if you don't need access to `LoadMap` (meaning BP mods won't load) is to set `HookLoadMap` to 0 in UE4SS-settings.ini.
It's not in the file right now but you can just add `HookLoadMap = 0` under the `[Hooks]` section.
