### ISSUE TITLE
[BUG - Release] toggledebugcamera not "untoggling"

### ISSUE THREAD

**Issue by acyc070** [UE4SS-RE/RE-UE4SS#514]
latest version
it happens only with ue 5 games

https://github.com/UE4SS-RE/RE-UE4SS/assets/112773735/e5a693d0-9d40-4ced-843a-d3160e5de1e5

**Comment by UE4SS** [comment]
I don't believe this is a UE4SS problem.
I've experienced similar problems with other console "unlockers".
Not entirely sure why it happens, but I'm very sure it's not an intrinsic problem of UE4SS.
It might have to do with what object the command actually targets, because you've detached from your character so it might not be executing on the right object.

**Comment by joric** [comment]
@UE4SS I confirm, my game doesn't untoggle either. But could you please tell 1) how to execute console command (`toggledebugcamera`) from lua; 2) how to reposess the player after that? It's just that `toggledebugcamera` provides much better controls that could be done in script, existing noclip mods struggle with the vertical motion.

**Comment by narknon** [comment]
This is related to normal UE functionality and playercontroller ownership of the debug camera. Not related to UE4SS.

**Comment by joric** [comment]
@narknon Scripting is related to UE4SS though. Particularly I'm looking for a way to execute console command from lua, is GEngine:Exec even available? The console is enabled but what's the API for executing a console command? I want to bind a shortcut to it. Maybe I could repossess the player from lua. It's just that that camera is much better than the character fly mode.
**Upd.** you can call console commands with `FindFirstOf("PlayerController").CheatManager["toggledebugcamera"]()` but repossessing it is still an issue. This doesn't work either (the camera just never turns off):
```lua
local UEHelpers = require("UEHelpers")
local originalController = nil
local function toggleDebugCamera()
    if inDebugCamera then
        print("Disabling", originalController)
        originalController.CheatManager:DisableDebugCamera() -- doesn't work
        local controllers = FindAllOf("PlayerController")
        print("Found", #controllers, "controllers")
        for _, pc in ipairs(controllers) do
            print("Disabling", pc, pc.CheatManager:IsValid())
            if pc and pc.CheatManager and pc.CheatManager:IsValid() and pc.CheatManager.DisableDebugCamera then
                pc.CheatManager:DisableDebugCamera() -- doesn't work either
                print("Disabled")
            end
        end
        inDebugCamera = false
    else
        originalController = UEHelpers.GetPlayerController()
        print("Enabling", originalController)
        UEHelpers.GetPlayerController().CheatManager:EnableDebugCamera() -- works
        inDebugCamera = true
    end
end
RegisterKeyBind(Key.Z, toggleDebugCamera)
```

```txt
[22:27:00.1273109] [Lua] Enabling		AActor: 0000023637A67578
[22:27:00.9466167] [Lua] Disabling		AActor: 0000023637A67578
[22:27:00.9936493] [Lua] Found		2		controllers
[22:27:00.9940137] [Lua] Disabling		AActor: 0000023637A67A78		true
[22:27:00.9942509] [Lua] Disabled
[22:27:00.9945251] [Lua] Disabling		AActor: 0000023637A65278		false
```

Apparently there are 3 controllers in the scene and one of them never has the valid cheat manager. I wish it was lua related but the console doesn't work either. Maybe it's lua related though because the newly created camera controller doesn't get it's own cheat manager?

**Comment by joric** [comment]
@narknon I solved the issue locally. It's still kind of ue4ss fault. You have to monitor newly created controllers and put new cheat manager onto them. Proof of concept:
```lua
local UEHelpers = require("UEHelpers")
local function toggleDebugCamera()
    if inDebugCamera then
        local pc = FindFirstOf("DebugCameraController")
        if not pc.CheatManager:IsValid() then
            pc.CheatManager = StaticConstructObject(StaticFindObject("/Script/Engine.CheatManager"), pc)
        end
        pc.CheatManager:DisableDebugCamera()
        inDebugCamera = false
    else
        UEHelpers.GetPlayerController().CheatManager:EnableDebugCamera()
        inDebugCamera = true
    end
end
RegisterKeyBind(Key.Z, toggleDebugCamera)
```

**Comment by UE4SS** [comment]
> [@narknon](https://github.com/narknon) I solved the issue locally. It's still kind of ue4ss fault. You have to monitor newly created controllers and put new cheat manager onto them. Proof of concept:

No it's not.
How is it our fault that UE has a broken command ?

**Comment by joric** [comment]
@UE4SS this patch fixes the issue with toggling and untoggling the camera from console. I tested it and it works, the camera controller gets the message from the console, it just needed a valid CheatManager because it's created in runtime after the plugin is loaded.

```patch
diff --git a/assets/Mods/CheatManagerEnablerMod/Scripts/main.lua b/assets/Mods/CheatManagerEnablerMod/Scripts/main.lua
index ea77e0f..6811891 100644
--- a/assets/Mods/CheatManagerEnablerMod/Scripts/main.lua
+++ b/assets/Mods/CheatManagerEnablerMod/Scripts/main.lua
@@ -30,3 +30,18 @@ RegisterHook("/Script/Engine.PlayerController:ClientRestart", function(self, New
         print("[CheatManagerEnabler] Was unable to construct CheatManager, therefore, could not enable Cheat Manager\n")
     end
 end)
+
+---@param PlayerController RemoteUnrealParam<APlayerController>
+NotifyOnNewObject("/Script/Engine.PlayerController", function(PlayerController)
+    if not PlayerController.CheatManager:IsValid() then
+        print("[CheatManagerEnabler] Adding Cheat Manager on NotifyOnNewObject")
+        local CheatManagerClass = StaticFindObject("/Script/Engine.CheatManager")
+        if CheatManagerClass:IsValid() then
+            local CreatedCheatManager = StaticConstructObject(CheatManagerClass, PlayerController)
+            if CreatedCheatManager:IsValid() then
+                print(string.format("[CheatManagerEnabler] Constructed CheatManager [0x%X]\n", CreatedCheatManager:GetAddress()))
+                PlayerController.CheatManager = CreatedCheatManager
+            end
+        end
+    end
+end)
```
Without this I also somehow managed to get invalid CheatManager on a regular UEHelpers.GetPlayerController() during the game.

This UE4SS fix is REALLY REALLY easy to verify, just type `toggledebugcamera` in console and check if it untoggles.

**Comment by jojusv** [comment]
Can confirm the fix posted by @joric completely fixes this issue!

I just added the extra function to the bottom of the main.lua and it works perfectly in games such as Abiotic Factor.
Please reconsider adding it to main.

**Comment by emoose** [comment]
The Code Vein 2 crash with CheatManagerEnablerMod enabled also seems fixed by the patch from @joric, many thanks!

E: hm, seems the existing RegisterHook probably wouldn't do much after this since it checks `CheatManager:IsValid()` and returns if set, and this NotifyOnNewObject hook would have set it before that.
Was thinking it could maybe be changed to a single NotifyOnNewObject hook instead of having both RegisterHook + NotifyOnNewObject, eg:

```
---@param PlayerController RemoteUnrealParam<APlayerController>
NotifyOnNewObject("/Script/Engine.PlayerController", function(PlayerController)
    if PlayerController.CheatManager:IsValid() then
        print("[CheatManagerEnabler] CheatManager already exist, skipping restoration\n")
        return
    end

    local CheatManagerClass = PlayerController.CheatClass
    if not CheatManagerClass:IsValid() then
        print("[CheatManagerEnabler] Controller:CheatClass is nullptr, using default CheatClass instead\n")

        CheatManagerClass = StaticFindObject("/Script/Engine.CheatManager") --[[@as UClass]]
    end

    if not CheatManagerClass:IsValid() then
        print("[CheatManagerEnabler] Couldn't find default CheatClass, therefore, could not enable Cheat Manager\n")
        return
    end

    local CreatedCheatManager = StaticConstructObject(CheatManagerClass, PlayerController)
    if CreatedCheatManager:IsValid() then
        print(string.format("[CheatManagerEnabler] Constructed CheatManager [0x%X]\n", CreatedCheatManager:GetAddress()))

        PlayerController.CheatManager = CreatedCheatManager
        print("[CheatManagerEnabler] Enabled CheatManager\n")
    else
        print("[CheatManagerEnabler] Was unable to construct CheatManager, therefore, could not enable Cheat Manager\n")
    end
end)
```

Looks like it can have issues with the `PlayerController.CheatClass` read though (would just crash when game started up), if I remove the CheatClass stuff and just use `local CheatManagerClass = StaticFindObject("/Script/Engine.CheatManager") --[[@as UClass]]` that seems to let it work.

E2: Changing the orig script to use `local CheatManagerClass = StaticFindObject("/Script/Engine.CheatManager")` instead of reading CheatClass also lets CV2 work, guess it was just an issue with the custom AppCheatManager they use then.

E3: Ahh CV2 also had the issue with untoggling though, but NotifyOnNewObject method does let it work.

**Comment by UE4SS** [comment]
@emoose Just fyi, if you want people to notice your updates, make a new comment instead of editing an existing one, otherwise notifications aren't sent.
