### ISSUE TITLE
Palworld - Altermatic Mod (Incompatibility will crash game 100%)

### ISSUE THREAD

**Issue by Thingey** [UE4SS-RE/RE-UE4SS#598]
I'm just posting it here for palworld users. (got a feeling some people are crashing due to this)
UE4SS works fine from vortex mod manager as long you don't use the mod named: Altermatic.
due to that mod's file "Altermatic.pak" will crash the game if paired with UE4SS.
(remove Altermatic.pak from your LogicMods folder if you wanna use UE4SS)
https://www.nexusmods.com/palworld/mods/1626?tab=posts&BH=0

So atm untill altermatic updates that file or UE4SS can support that file somehow? you need to play with mod's that run UE4SS or mod's like Altermatic and other mod's that does not rely on UE4SS to run, not both at same time!
(Reported this behaviour on Altermatic as well since I would believe the issue is on their end, not UE4SS but I'm not sure)

You can try install everythign manually without vortex mod manager and see (since that part is untested)

**Comment by Corgano** [comment]
It's a bit premature to post a bug report

Installing ue4ss and altermatic on a clean install works perfectly fine when you don't use vortex. Right now vortex support for palworld is new and has known bugs / incompatibilities, as vortex regularly places palworld mod files in the wrong location and generally breaks things.

As far as the three way combo of vortex, altermatic, and ue4ss is true only because _vortex_ is in the equation.

**Comment by Thingey** [comment]
Yea, I only started crashing due to people recommending "Use vortex for automatic updating the mods". LoL

**Comment by Buckminsterfullerene02** [comment]
Aside from it clearly being a vortex skill issue, we also do not provide hardcoded support for other tools, games or mods.

I don't think there is any use keeping this issue open as people should still be searching closed issues for potential solutions to their problems.
