### ISSUE TITLE
[BUG - Release] Unable to Build Latest Main at time of writing.

### ISSUE THREAD

**Issue by portalmaster137** [UE4SS-RE/RE-UE4SS#615]
I've been trying to build the latest main build (07bb2dd), and no matter what i do, it keeps failing to build.

Here are my commands in order, with the xmake log attached.
```
git clone git@github.com:UE4SS-RE/RE-UE4SS.git
cd .\RE-UE4SS\
git submodule update --init --recursive
xmake f -m "Game__Shipping__Win64"
xmake -vD
```
I Beleive this is an error with one of the submodules (the UEPseudo), as i cant get that to build separately either, i've also tried for hours to get this work but i've had no luck, so people smarter than me can hopefully fix this issue.

[xmake_log.txt](https://github.com/user-attachments/files/16571303/xmake_log.txt)

**Comment by UE4SS** [comment]
I don't have a solution for you other than defining `EAspectRatioAxisConstraint` yourself somewhere.
The underlying problem is UVTD generating forward declarations for enums when that's prohibited in C++.
The solution is to fix UVTD.
That said, no one else seems to be having this problem so clearly MSVC has implemented some kind of compiler extension to allow this behavior or it's a compiler bug.
Regardless, I don't know why you have this problem and no one else.

**Comment by portalmaster137** [comment]
Would it be worth it to reinstall visual studio from the ground up? Could it also be possible that 2022 Preview is somehow messing it up?

**Comment by portalmaster137** [comment]
Found the problem!
It was MSVC Itself, 19.41, aka Visual Studio 2022 Preview Would NOT Compile, however 19.40, which is used in normal VS2022, works just fine. I'm thinking MSVC 19.41 Disables forward decleration of enums or somthing, but it builds now. Maybe make this a check in xmake or put in the readme to use 19.40?
